### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by chdown** [Xigong93/XiaoZhuan#10]
windows10运行后，无法正常运行显示，窗口显示为空，如下图：
![image](https://github.com/user-attachments/assets/1ea41ece-ab65-4e18-8efa-a9f7ee2767e4)

**Comment by Xigong93** [comment]
你好，麻烦截图截全一点，这个图片太小，太模糊了，看不清楚是什么情况。

**Comment by chdown** [comment]
我截图的是最近任务的截图，场景就是打开exe后没有界面，点击任务栏中 小篆传包 也没有任何反应，看了下也没有日志文件

**Comment by chdown** [comment]
我后续有时间，运行源码看下情况吧

**Comment by chdown** [comment]
> 你好，麻烦截图截全一点，这个图片太小，太模糊了，看不清楚是什么情况。

我运行源码，遇到下面的错误

![1727416531879_04C545B1-9D3B-429f-86F8-890C43A6B17C](https://github.com/user-attachments/assets/e3844b60-be45-4f14-9089-90e2f48a2ccb)

看到 [compose-multiplatform](https://github.com/JetBrains/compose-multiplatform/issues/3757) 有错误，但是升级到compose.version=1.6.11 无效，修改透明度生效，可以正常运行

![image](https://github.com/user-attachments/assets/ee9b89e7-0118-49ea-938a-1ebd9f0675ba)
